CREATE TABLE "GCG_6700_Earned" (
 "BIRUNID" BIGINT,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "PART" CHAR(20),
 "EST_HOURS_WORKED" DOUBLE,
 "PIECES_COMPLTD" DOUBLE,
 "WORKGROUP" CHAR(4));
 
 CREATE INDEX "GCG_6700_Earned" ON "GCG_6700_Earned"("BIRUNID");