CREATE TABLE "GCG_6700_Actual" (
 "BIRUNID" BIGINT,
 "EMPL" CHAR(6),
 "NAME" CHAR(30),
 "HOURS_WORKED" DOUBLE,
 "WORKGROUP" CHAR(4));
 
 CREATE INDEX "GCG_6700_Actual" ON "GCG_6700_Actual"("BIRUNID");